# Generated by Django 5.2.5 on 2025-08-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('charged_to', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('receipt_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawal_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked', 'Locked')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
