# Generated by Django 5.2.5 on 2025-09-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Locked', 'Locked')], default='Pending', max_length=20),
        ),
    ]
